version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

    logging:
      driver: none

  rabbit:
    image: rabbitmq:management
    environment:
      RABBITMQ_LOGS: 0
    ports:
      - "15672:15672"
      - "5672:5672"
